apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-admin-template
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  selector:
    app: {{ .Release.Name }}-template
  type: ClusterIP
  ports:
    - port: {{ .Values.adminClusterIp.port }}
      name: grpc-web #port name should have prefix of grpc-web to instruct istio with the app protocol
      targetPort: {{ .Values.adminClusterIp.targetPort }}
      protocol: TCP
