apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-template
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  host: {{ .Release.Name }}-public-template
  subsets:
    - name: v1
      labels:
        version: v1